### ISSUE TITLE
Using PHP in 2018

### ISSUE THREAD

**Issue by LordNature** [SDCore/DCLVTC#1]
`--start satire--`
Your inferior programming language should be changed. PHP is quite disgusting to say the least. The error interpreter is terrible and it is terrible. Please consider changing to more superior language like C, Javascript (Node.js) or anything else. At least you are using PHP over .NET.

For the people auditing your source code, please leave some context clues as to what information lies within the code. Consider adding a README.md and LICENSE. Honestly, I would assume you would know better.
`--end satire--`

**Comment by SDCore** [comment]
I have taken this into consideration and decided to close the project.

// Issue Closed->Closed Project
